'use client';

import React, { useState, useCallback } from 'react';
import TopBar from '@/components/TopBar';
import { useApi } from '@/hooks/useApi';
import { Bell, Send, Copy, CheckCircle2, Clock, XCircle, RefreshCw } from 'lucide-react';

type Notification = {
  id: string;
  demo_booking_id: string;
  notification_type: 'team_alert' | 'parent_reminder';
  channel: 'slack' | 'whatsapp';
  recipient: string;
  message_body: string;
  status: 'pending' | 'sent' | 'failed';
  created_at: string;
  demo_bookings: {
    student_name: string | null;
    guardian_name: string | null;
    student_contact: string | null;
  } | null;
};

type ApiResp = { ok: boolean; data: Notification[]; count: number | null };

const PAGE_SIZE = 50;

const STATUS_TABS = ['all', 'pending', 'sent', 'failed'] as const;
type StatusTab = (typeof STATUS_TABS)[number];

const statusCfg = (s: string) => {
  switch (s) {
    case 'sent':    return { color: '#10b981', bg: '#ecfdf5', Icon: CheckCircle2, label: 'Sent' };
    case 'failed':  return { color: '#ef4444', bg: '#fef2f2', Icon: XCircle,      label: 'Failed' };
    default:        return { color: '#f59e0b', bg: '#fffbeb', Icon: Clock,         label: 'Pending' };
  }
};

const channelLabel = (ch: string) =>
  ch === 'slack' ? '💬 Slack' : '📱 WhatsApp';

const typeLabel = (t: string) =>
  t === 'team_alert' ? 'Team Alert' : 'Parent Reminder';

export default function NotificationsPage() {
  const [tab, setTab]           = useState<StatusTab>('all');
  const [page, setPage]         = useState(0);
  const [sending, setSending]   = useState<Record<string, boolean>>({});
  const [localStatus, setLocalStatus] = useState<Record<string, string>>({});

  const statusParam = tab !== 'all' ? `&status=${tab}` : '';
  const url = `/api/notifications?limit=${PAGE_SIZE}&offset=${page * PAGE_SIZE}${statusParam}`;
  const { data, loading, refetch } = useApi<ApiResp>(url);

  const total      = data?.count ?? 0;
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));
  const rows       = data?.data ?? [];

  const pendingCount = rows.filter(r => (localStatus[r.id] ?? r.status) === 'pending').length;

  function changeTab(t: StatusTab) { setTab(t); setPage(0); }

  const send = useCallback(async (n: Notification) => {
    setSending((p) => ({ ...p, [n.id]: true }));
    try {
      const res = await fetch('/api/notify', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          notificationId: n.id,
          channel:   n.channel,
          recipient: n.recipient,
          message:   n.message_body,
        }),
      });
      const json = await res.json();
      setLocalStatus((p) => ({ ...p, [n.id]: json.ok ? 'sent' : 'failed' }));
    } finally {
      setSending((p) => ({ ...p, [n.id]: false }));
    }
  }, []);

  const markSent = useCallback(async (id: string) => {
    setLocalStatus((p) => ({ ...p, [id]: 'sent' }));
    await fetch('/api/notifications', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ id, status: 'sent' }),
    });
  }, []);

  return (
    <div className="animate-fade-in">
      <TopBar searchPlaceholder="Search notifications…" />

      <div style={{ marginBottom: '1.25rem' }}>
        <h2 style={{ fontSize: '1.25rem', fontWeight: 800, marginBottom: 4 }}>Notification Center</h2>
        <p style={{ fontSize: '0.85rem', color: 'var(--muted)' }}>
          WhatsApp parent reminders &amp; Slack team alerts generated by AI scoring
        </p>
      </div>

      {/* Tabs + refresh */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1.25rem' }}>
        {STATUS_TABS.map((t) => (
          <button
            key={t}
            onClick={() => changeTab(t)}
            style={{
              padding: '0.5rem 1rem', borderRadius: 10, fontWeight: 600, fontSize: '0.8rem',
              background: tab === t ? 'var(--foreground)' : 'var(--surface)',
              color: tab === t ? 'var(--surface)' : 'var(--muted)',
              border: `1px solid ${tab === t ? 'var(--foreground)' : 'var(--border-strong)'}`,
              cursor: 'pointer', textTransform: 'capitalize',
            }}
          >
            {t}
          </button>
        ))}
        <button
          onClick={refetch}
          className="btn-ghost"
          style={{ marginLeft: 'auto', gap: '0.5rem' }}
        >
          <RefreshCw size={14} />
          Refresh
        </button>
      </div>

      {/* Stats bar */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem', marginBottom: '1.25rem' }}>
        {[
          { label: 'Total', value: total, color: 'var(--foreground)' },
          { label: 'Pending', value: null, color: '#f59e0b' },
          { label: 'Sent', value: null, color: '#10b981' },
        ].map((s, i) => (
          <div key={i} className="card" style={{ padding: '1rem 1.25rem' }}>
            <div style={{ fontSize: '0.72rem', color: 'var(--muted-foreground)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 6 }}>
              {s.label}
            </div>
            <div style={{ fontSize: '1.5rem', fontWeight: 800, color: s.color }}>
              {loading ? '—' : (
                i === 0 ? total.toLocaleString() :
                i === 1 ? (data?.data ?? []).filter(r => (localStatus[r.id] ?? r.status) === 'pending').length.toLocaleString() :
                          (data?.data ?? []).filter(r => (localStatus[r.id] ?? r.status) === 'sent').length.toLocaleString()
              )}
            </div>
          </div>
        ))}
      </div>

      {/* Table */}
      <div className="card-lg" style={{ overflow: 'hidden' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
          <thead>
            <tr style={{ borderBottom: '1px solid var(--border)' }}>
              {['Lead', 'Type', 'Channel', 'Recipient', 'Message Preview', 'Created', 'Status', 'Actions'].map((h) => (
                <th key={h} style={{ padding: '0.875rem 1rem', fontSize: '0.72rem', fontWeight: 700, color: 'var(--muted-foreground)', textTransform: 'uppercase', letterSpacing: '0.06em', whiteSpace: 'nowrap' }}>
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {loading ? (
              Array.from({ length: 6 }).map((_, i) => (
                <tr key={i}>
                  {Array.from({ length: 8 }).map((__, j) => (
                    <td key={j} style={{ padding: '0.875rem 1rem' }}>
                      <div style={{ height: 16, background: '#f1f5f9', borderRadius: 6, width: j === 4 ? 180 : 80 }} />
                    </td>
                  ))}
                </tr>
              ))
            ) : rows.length === 0 ? (
              <tr>
                <td colSpan={8} style={{ padding: '2.5rem', textAlign: 'center', color: 'var(--muted-foreground)', fontSize: '0.875rem' }}>
                  <Bell size={24} style={{ marginBottom: 8, opacity: 0.3, display: 'block', margin: '0 auto 8px' }} />
                  No notifications yet — they are generated automatically when duplicate leads are scored.
                </td>
              </tr>
            ) : rows.map((n) => {
              const st = localStatus[n.id] ?? n.status;
              const cfg = statusCfg(st);
              const { Icon } = cfg;
              const isSending = sending[n.id];
              const booking = n.demo_bookings;

              return (
                <tr key={n.id} style={{ borderBottom: '1px solid var(--border)' }}>
                  <td style={{ padding: '0.875rem 1rem' }}>
                    <div style={{ fontWeight: 600, fontSize: '0.8rem' }}>
                      {booking?.guardian_name ?? booking?.student_name ?? '—'}
                    </div>
                    <div style={{ fontSize: '0.7rem', color: 'var(--muted-foreground)' }}>
                      {booking?.student_contact ?? '—'}
                    </div>
                  </td>
                  <td style={{ padding: '0.875rem 1rem', fontSize: '0.8rem', whiteSpace: 'nowrap' }}>
                    {typeLabel(n.notification_type)}
                  </td>
                  <td style={{ padding: '0.875rem 1rem', fontSize: '0.8rem', whiteSpace: 'nowrap' }}>
                    {channelLabel(n.channel)}
                  </td>
                  <td style={{ padding: '0.875rem 1rem', fontSize: '0.75rem', color: 'var(--muted)', maxWidth: 120, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                    {n.recipient}
                  </td>
                  <td style={{ padding: '0.875rem 1rem', maxWidth: 220 }}>
                    <div style={{ fontSize: '0.75rem', color: 'var(--muted)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                      {n.message_body?.slice(0, 80)}…
                    </div>
                  </td>
                  <td style={{ padding: '0.875rem 1rem', fontSize: '0.75rem', color: 'var(--muted-foreground)', whiteSpace: 'nowrap' }}>
                    {n.created_at ? new Date(n.created_at).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—'}
                  </td>
                  <td style={{ padding: '0.875rem 1rem' }}>
                    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 5, background: cfg.bg, color: cfg.color, padding: '0.2rem 0.6rem', borderRadius: 999, fontSize: '0.72rem', fontWeight: 700 }}>
                      <Icon size={11} /> {cfg.label}
                    </span>
                  </td>
                  <td style={{ padding: '0.875rem 1rem' }}>
                    <div style={{ display: 'flex', gap: 6 }}>
                      <button
                        onClick={() => navigator.clipboard.writeText(n.message_body ?? '')}
                        className="icon-btn"
                        title="Copy message"
                        style={{ width: 28, height: 28, borderRadius: 7 }}
                      >
                        <Copy size={12} />
                      </button>
                      {st === 'pending' && (
                        <>
                          <button
                            onClick={() => send(n)}
                            disabled={isSending}
                            className="btn-primary"
                            style={{ padding: '0.25rem 0.625rem', fontSize: '0.72rem', borderRadius: 7, gap: 4 }}
                          >
                            <Send size={11} />
                            {isSending ? '…' : 'Send'}
                          </button>
                          <button
                            onClick={() => markSent(n.id)}
                            className="btn-ghost"
                            style={{ padding: '0.25rem 0.5rem', fontSize: '0.72rem', borderRadius: 7 }}
                            title="Mark as sent manually"
                          >
                            <CheckCircle2 size={11} />
                          </button>
                        </>
                      )}
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Pagination */}
      {!loading && total > PAGE_SIZE && (
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: '1rem' }}>
          <span style={{ fontSize: '0.8rem', color: 'var(--muted-foreground)' }}>
            Showing {page * PAGE_SIZE + 1}–{Math.min((page + 1) * PAGE_SIZE, total)} of {total.toLocaleString()}
          </span>
          <div style={{ display: 'flex', gap: 8 }}>
            <button onClick={() => setPage((p) => Math.max(0, p - 1))} disabled={page === 0} className="btn-ghost" style={{ padding: '0.375rem 0.75rem', fontSize: '0.8rem' }}>
              ← Prev
            </button>
            <button onClick={() => setPage((p) => Math.min(totalPages - 1, p + 1))} disabled={page >= totalPages - 1} className="btn-ghost" style={{ padding: '0.375rem 0.75rem', fontSize: '0.8rem' }}>
              Next →
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
